package edu.iastate.cs472.proj1;

import java.io.FileNotFoundException;

import java.io.File;
import java.io.FileNotFoundException;
import java.util.Scanner;
import java.util.Arrays;

/**
 *  
 * @author Jackson Mears
 *
 */

public class PuzzleSolver 
{
	/**
	 *  Read an initial state from the input file.  Solve the eight puzzle three times:
	 *  
	 *      1) The first solution allows single moves only and uses the heuristic based on the number
	 *         of mismatched tiles. 
	 *         
	 *      2) The second solution also allows single moves only but uses the heuristic based on the 
	 *         Manhattan distance. 
	 *         
	 *      3) The third solution allows single and double moves and uses the admissible heuristic 
	 *         designed by yourself.  
	 *         
	 *  Each solution is printed out as a sequence of states, generated by single/double moves, from the 
	 *  initial state to the goal state. If no solution exists, report it.  
	 * 
	 * @param args
	 * @throws FileNotFoundException if the input file does not exist 
	 * @throws IllegalArgumentException if the initial state from the file is not in the correct format
	 */
    
    public static void main(String[] args) throws FileNotFoundException, IllegalArgumentException
    {
        Scanner scanner = new Scanner(new File("input/8Puzzle.txt"));

        int[] input = new int[9];

        for (int i = 0; i < 9; i++)
        {
            input[i] = scanner.nextInt();
        }

        scanner.close();

        State initial_state = new State(input);

        System.out.println(EightPuzzle.solve8Puzzle(initial_state));
    }


}
