package edu.iastate.cs472.proj1;

import java.io.FileNotFoundException;
import java.util.Arrays;

/**
 *  
 * @author Jackson Mears
 *
 */


/**
 * This class represents a board configuration in the 8-puzzle.  Only the initial configuration is 
 * generated by a constructor, while intermediate configurations will be generated via calling
 * the method successorState().  State objects will form two circular doubly-linked lists OPEN and 
 * CLOSED, which will be used by the A* algorithm to search for a path from a given initial board
 * configuration to the final board configuration below: 
 * 
 *  1 2 3 
 *  8   4
 *  7 6 5
 *
 * The final configuration (i.e., the goal state) above is not explicitly represented as an object 
 * of the State class. 
 */

public class State implements Cloneable, Comparable<State>
{
    public static final int[]   STATE_GOAL = {1, 2, 3, 8, 0, 4, 7, 6, 5};
    public static int           state_counter = 1;
	public static Heuristic     heuristic; // heuristic used. shared by all the states. 

    public int      id;

	public int[]    board; 		// configuration of tiles 
	
	public State    previous;    	// previous node on the OPEN/CLOSED list
	public State    next; 			// next node on the OPEN/CLOSED list
	public State    predecessor; 	// predecessor node on the path from the initial state 
	
	public Move     move;           // the move that generated this state from its predecessor
	public int      moves_count; 	    // number of moves from the initial state to this state

	
	private int     mismatched_tiles_count = -1;    // number of mismatched tiles between this state 
	                                        // and the goal state; negative if not computed yet.
	private int     manhattan_distnace = -1;     // Manhattan distance between this state and the 
	                                        // goal state; negative if not computed yet. 
	private int     single_and_double_moves_count = -1;  // number of single and double moves with each double 
										    // move counted as one; negative if not computed yet. 

	
	/**
	 * Constructor (for the initial state).  
	 * 
	 * It takes a 2-dimensional array representing an initial board configuration. The empty 
	 * square is represented by the number 0.  
	 * 
	 *     a) Initialize all three links previous, next, and predecessor to null.  
	 *     b) Set move to null and numMoves to zero.
	 * 
	 * @param board
	 * @throws IllegalArgumentException		if board is not a 3X3 array or its nine entries are 
	 * 										not respectively the digits 0, 1, ..., 8. 
	 */
    public State(int[] _input) throws IllegalArgumentException 
    {
        this.board          = _input;

        state_counter++;
        this.id             = state_counter;

        this.previous       = null;
        this.next           = null;
        this.predecessor    = null;
        this.move           = null;

        this.moves_count    = 0;
    }    
    /**
     * Constructor (for the initial state) 
     * 
     * It takes a state from an input file that has three rows, each containing three digits 
     * separated by exactly one blank.  Every row starts with a digit. The nine digits are 
     * from 0 to 8 with no duplicates.  
     * 
     * Do the same initializations as for the first constructor. 
     * 
     * @param inputFileName
     * @throws FileNotFoundException
     * @throws IllegalArgumentException  if the file content does not meet the above requirements. 
     */
    public State (String inputFileName) throws FileNotFoundException, IllegalArgumentException
    {
    	
    	// (I will return to this if I chose to implement the interactive portion)
	}
    



    private int findBlankSquare(int[] board)
    {
        for (int i = 0; i < 9; i++)
        {
            if (board[i] == 0)
            {
                return i;
            }
        }
        return -1;
    }
    
    /**
     * Generate the successor state resulting from a given move.  Throw an exception if the move 
     * cannot be executed.  Besides setting the array board[][] properly, you also need to do the 
     * following:
     * 
     *     a) set the predecessor of the successor state to this state;
     *     b) set the private instance variable move of the successor state to the parameter m; 
     *     c) Set the links next and previous to null;  
     *     d) Set the variable numMoves for the successor state to this.numMoves + 1. 
     * 
     * @param m  one of the moves LEFT, RIGHT, UP, DOWN, DBL_LEFT, DBL_RIGHT, DBL_UP, and DBL_DOWN
     * @return null  			if the successor state is this.predecessor
     *         successor state  otherwise 
     * @throws IllegalArgumentException if LEFT when the empty square is in the right column, or  
     *                                  if RIGHT when the empty square is in the left column, or
     *                                  if UP when the empty square is in the bottom row, or 
     *                                  if DOWN when the empty square is in the top row, or
     *                                  if DBL_LEFT when the empty square is not in the left column, or 
     *                                  if DBL_RIGHT when the empty square is not in the right column, or 
     *                                  if DBL_UP when the empty square is not in the top row, or 
     *                                  if DBL_DOWN when the empty square is not in the bottom row. 
     */                                  
    public State successorState(Move m) throws IllegalArgumentException
    {
        int blank       = findBlankSquare(this.board);
        int[] newBoard  = this.board.clone();

        switch (m)
        {

            case LEFT:
                if (blank % 3 == 0) throw new IllegalArgumentException("Cannot move LEFT");
                newBoard[blank]         = newBoard[blank - 1];
                newBoard[blank - 1]     = 0;
                break;

            case RIGHT:
                if (blank % 3 == 2) throw new IllegalArgumentException("Cannot move RIGHT");
                newBoard[blank]         = newBoard[blank + 1];
                newBoard[blank + 1]     = 0;
                break;

            case UP:
                if (blank < 3) throw new IllegalArgumentException("Cannot move UP");
                newBoard[blank]         = newBoard[blank - 3];
                newBoard[blank - 3]     = 0;
                break;

            case DOWN:
                if (blank >= 6) throw new IllegalArgumentException("Cannot move DOWN");
                newBoard[blank]         = newBoard[blank + 3];
                newBoard[blank + 3]     = 0;
                break;


            case DBL_LEFT:
                if (blank % 3 != 2) throw new IllegalArgumentException("Cannot move DBL_LEFT");
                newBoard[blank]         = newBoard[blank - 1];
                newBoard[blank - 1]     = newBoard[blank - 2];
                newBoard[blank - 2]     = 0;
                break;

            case DBL_RIGHT:
                if (blank % 3 != 0) throw new IllegalArgumentException("Cannot move DBL_RIGHT");
                newBoard[blank]         = newBoard[blank + 1];
                newBoard[blank + 1]     = newBoard[blank + 2];
                newBoard[blank + 2]     = 0;
                break;

            case DBL_UP:
                if (blank < 6) throw new IllegalArgumentException("Cannot move DBL_UP");
                newBoard[blank]         = newBoard[blank - 3];
                newBoard[blank - 3]     = newBoard[blank - 6];
                newBoard[blank - 6]     = 0;
                break;

            case DBL_DOWN:
                if (blank >= 3) throw new IllegalArgumentException("Cannot move DBL_DOWN");
                newBoard[blank]         = newBoard[blank + 3];
                newBoard[blank + 3]     = newBoard[blank + 6];
                newBoard[blank + 6]     = 0;
                break;

            default:
                throw new IllegalArgumentException("Invalid move");
        }

        State child         = new State(newBoard);

        child.predecessor   = this;
        child.move          = m;
        child.previous      = null;
        child.next          = null;
        child.moves_count   = this.moves_count + 1;

        if (this.predecessor != null && child.equals(this.predecessor)) return null;

        return child;
    }        
    /**
     * Determines if the board configuration in this state can be rearranged into the goal configuration. 
     * According to the PowerPoint notes that introduce the 8-puzzle, we check if this state has an odd number 
     * of inversions. 
     */
    /**
     * 
     * @return true if the puzzle starting in this state can be rearranged into the goal state.
     */

    // using a fenwick tree solution!! could've just as easily done a simple brute force solution which would've been a fine solution given the static size of the 8-puzzle problem
   public boolean solvable()
    {
        int[] bit           = new int[10];
        int inversions      = 0;

        for (int i = 8; i >= 0; i--)
        {
            if (board[i] == 0) continue;

            int value   = board[i];
            int count   = 0;
            int x       = value - 1;

            while (x > 0)
            {
                count   += bit[x];
                x       -= x & -x;
            }

            inversions  += count;
            x           = value;

            while (x <= 9)
            {
                bit[x]++;
                x += x & -x;
            }
        }

        return inversions % 2 == 1;
    } 
    /**
     * Check if this state is the goal state, namely, if the array board[][] stores the following contents: 
     * 
     * 		1 2 3 
     * 		8 0 4 
     * 		7 6 5 
     * 
     * @return
     */
    public boolean isGoalState()
    {

        for (int i = 0; i < 9; i++)
        {
            if (this.board[i] != STATE_GOAL[i]) return false;
        }
    	
    	return true; 
    }
    
    
    /**
     * Write the board configuration according to the following format:
     * 
     *     a) Output row by row in three lines with no indentations.  
     *     b) Two adjacent tiles in each row have exactly one blank in between. 
     *     c) The empty square is represented by a blank.  
     *     
     * For example, 
     * 
     * 2   3
     * 1 8 4
     * 7 6 5  
     * 
     */
    @Override 
    public String toString()
    {
        String result = "";

        for (int i = 0; i < 9; i++)
        {
            result += (board[i] == 0)   ? " "   : board[i];
            result += (i % 3 == 2)      ? "\n"  : " ";
        }

        return result;
    } 
    
    /**
     * Create a clone of this State object by copying over the board[][]. Set the links previous,
     * next, and predecessor to null. 
     * 
     * The method is called by SuccessorState(); 
     */
    @Override
    public Object clone()
    {
        State child = new State(this.board.clone());

        return child;
    } 

    /**
     * Compare this state with the argument state.  Two states are equal if their arrays board[][] 
     * have the same content.
     */
    @Override
    public boolean equals(Object o)
    {
        if (this == o) return true;

        if (!(o instanceof State)) return false;

        State s = (State) o;

        return Arrays.equals(this.board, s.board);
    }    
    /**
     * Evaluate the cost of this state as the sum of the number of moves from the initial state and 
     * the estimated number of moves to the goal state using the heuristic stored in the instance 
     * variable heu. 
     * 
     * If heu == TileMismatch, add up numMoves and the return values from computeNumMismatchedTiles().
     * If heu == MahattanDist, add up numMoves and the return values of computeMahattanDistance(). 
     * If heu == DoubleMoveHeuristic, add up numMoves and the return value of computeNumSingleDoubleMoves(). 
     * 
     * @return estimated number of moves from the initial state to the goal state via this state.
     * @throws IllegalArgumentException if heuristic is none of TileMismatch, MahattanDist, DoubleMoveHeuristic. 
     */
    public int cost() throws IllegalArgumentException
    {
        switch (heuristic)
        {
            case tile_mismatch: return moves_count + mismatchedTilesCompute();

            case manhattan_distance: return moves_count + manhattanDistanceCompute();

            case double_move: return moves_count + singleDoubleMovesCompute();

            default: throw new IllegalArgumentException("Invalid heuristic");
        }
    }
    
    /**
     * Compare two states by the cost. Let c1 and c2 be the costs of this state and the argument state s.
     * 
     * @return -1 if c1 < c2 
     *          0 if c1 = c2 
     *          1 if c1 > c2 
     *          
     * Call the method cost(). This comparison will be used in maintaining the OPEN list by the A* algorithm.
     */
    @Override
    public int compareTo(State s)
    {
        int c1 = this.cost();
        int c2 = s.cost();

        if (c1 < c2) return -1;

        if (c1 > c2) return 1;

        return 0;
    } 

    /**
     * Return the value of the private variable numMismatchedTiles if it is non-negative, and compute its 
     * value otherwise. 
     * 
     * @return the number of mismatched tiles between this state and the goal state. 
     */
    private int mismatchedTilesCompute()
    {
        if (mismatched_tiles_count >= 0) return mismatched_tiles_count;

        int count = 0;

        for (int i = 0; i < 9; i++)
        {
            if (board[i] != 0 && board[i] != STATE_GOAL[i]) count++;
        }

        mismatched_tiles_count = count;

        return count;
    }
	
	/**
	 * Return the value of the private variable ManhattanDistance if it is non-negative, and compute its value 
	 * otherwise.
	 * 
	 * @return the Manhattan distance between this state and the goal state. 
	 */

    // this is the only method where the single array complicates things, otherwise, for the most part, it has been a much simpler implmentation than the matrix int[][]
    private int manhattanDistanceCompute()
    {
        if (manhattan_distnace >= 0) return manhattan_distnace;

        int distance = 0;

        for (int i = 0; i < 9; i++)
        {
            int tile = board[i];

            if (tile == 0) continue;

            int row             = i / 3;
            int col             = i % 3;
            int goal_index      = 0;

            for (int j = 0; j < 9; j++)
            {
                if (STATE_GOAL[j] == tile)
                {
                    goal_index = j;
                    break;
                }
            }

            distance        += Math.abs(row - goal_index/3);
            distance        += Math.abs(col - goal_index % 3);
        }

        manhattan_distnace = distance;

        return distance;
    }	
	/**
	 * Return the value of the private variable numSingleDoubleMoves if it is non-negative, and compute its value 
	 * otherwise. 
	 * 
	 * @return the value of the private variable numSingleDoubleMoves that bounds from below the number of moves, 
	 *         single or double, which will take this state to the goal state.
	 */
    private int singleDoubleMovesCompute()
    {
        if (single_and_double_moves_count >= 0) return single_and_double_moves_count;

        single_and_double_moves_count = (int) Math.ceil(manhattanDistanceCompute() / 2.0);

        return single_and_double_moves_count;
    }


}
